import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ReactLenis } from "@/utils/lenis";

import Header from "@/components/Header";

const satoshi = localFont({
  src: [
    {
      path: "./fonts/Satoshi-Variable.woff2",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-VariableItalic.woff2",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className={`${satoshi.className} antialiased`}>
          <Header />
          {children}
          <footer></footer>
        </body>
      </ReactLenis>
    </html>
  );
}
